spring:
  shardingsphere: 
    datasource:
      names: master,slave
      master: 
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/geek_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC 
        username: root
        password: 123456
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/geek_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: 
    masterslave:
      load-balance-algorithm-type: round_robin
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave
    props: 
      sql:
        show: true
  main:
    allow-bean-definition-overriding: true
    
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.rexxar.batch_inser.domain
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080